version: '3.7'
services:
  csvserver:
    image: infracloudio/csvserver:latest 
    volumes:
      - .\InputFile:/csvserver/inputdata
    ports:
      - 9393:9300
    environment:
      - CSVSERVER_BORDER=Orange