version: '3.7'
services:
  csvserver:
    image: infracloudio/csvserver:latest 
    volumes:
      - .\InputFile:/csvserver/inputdata
    ports:
      - 9393:9300
    environment:
      - CSVSERVER_BORDER=Orange
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - .\prometheus.yml:/etc/prometheus/prometheus.yml
